version: '3'

services:
    db:
        restart: always
        image: postgres:latest
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: postgres
        volumes:
            - ./db/data:/var/lib/pgsql/data
            - ./db/init:/docker-entrypoint-initdb.d/
        ports:
            - 5432:5432
    api:
        restart: always
        build: ./
        env_file:
            - .env
        environment:
            DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
        ports:
            - 8080:8080
        depends_on:
            - db